#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4    # Use the Super key as the main modifier

# state controls
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-w close_or_remove

# application shortcuts
hc keybind $Mod-Return spawn st 
hc keybind $Mod-s spawn ~/scripts/screenshot.sh 
hc keybind $Mod-o spawn ~/scripts/menus/zathura.sh 

# sound
hc keybind $Mod-u spawn sh -c "pactl set-sink-mute 0 false ; pactl set-sink-volume 0 +5%" 
hc keybind $Mod-d spawn sh -c "pactl set-sink-mute 0 false ; pactl set-sink-volume 0 -5%"
hc keybind $Mod-0 spawn pactl set-sink-mute 0 toggle
hc keybind $Mod-Alt-0 spawn pactl set-source-mute 1 toggle

# menus
hc keybind $Mod-space spawn ~/scripts/menus/drun.sh
hc keybind $Mod-Tab spawn ~/scripts/menus/tags.sh

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
#split and focus in all directions
hc keybind $Mod-Control-h	chain , split left 0.5 , focus left
hc keybind $Mod-Control-j	chain , split bottom 0.5 , focus down
hc keybind $Mod-Control-k	chain , split top 0.5 , focus up
hc keybind $Mod-Control-l	chain , split right 0.5 , focus right
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode
hc keybind $Mod-Control-w remove

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Alt-h       resize left +$resizestep
hc keybind $Mod-Alt-j       resize down +$resizestep
hc keybind $Mod-Alt-k       resize up +$resizestep
hc keybind $Mod-Alt-l       resize right +$resizestep

# tags
hc add second
hc use default

# move focused window to next or previous tag
hc keybind $Mod-Shift-period move_index +1 --skip-visible
hc keybind $Mod-Shift-comma move_index -1 --skip-visible
# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-f floating toggle
hc keybind $Mod-m fullscreen toggle
hc keybind $Mod-z set_attr clients.focus.minimized toggle
hc keybind $Mod-t pseudotile toggle

#unminimizes all minimized windows
hc keybind $Mod-Shift-z \
   substitute FOCUS "tags.focus.name" \
   foreach CLIENT clients. \
     sprintf MINATT "%c.minimized" CLIENT \
     sprintf TAGATT "%c.tag" CLIENT and \
       , compare MINATT "=" "true" \
       , compare TAGATT "=" FOCUS \
       , set_attr MINATT false

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-c                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 horizontal vertical \
               , cycle_layout +1 horizontal vertical grid

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# --- THEME ---
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

## frame
hc set smart_frame_surroundings on
hc set frame_border_active_color '#68956a'
hc set frame_border_normal_color '#101010'
hc set frame_border_width 0
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 5
hc set frame_padding 0

## title
hc attr theme.title_when never

## window
hc set window_gap 0
hc attr theme.inner_width 0
hc attr theme.outer_width 0
hc attr theme.border_width 3
hc attr theme.padding_top 3
hc attr theme.padding_bottom 0
hc attr theme.urgent.color '#7811A1'
# theme.active.color and theme.normal.color are not set here, only at the end by the theme script

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
hc rule class='feh' floating=on
	#Rules for floating xterm
hc rule title='floating_xterm' floating=on
hc rule title='floating_xterm' floating_geometry=800x500
hc rule title='floating_xterm' floatplacement=center
	#Rules for volume display
hc rule title='volume_display' floating=on
hc rule title='volume_display' floating_geometry=80x60
hc rule title='volume_display' floatplacement=center
hc rule title='volume_display' focus=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

hc detect_monitors
hc pad 0 10 10 10 10

#set themed elements based on the set theme 
theme=$(cat ~/.config/theme)
~/.config/colors/herbstluftwm/$theme.sh
#check if the theme set is time-appropriate; if not, change it
/home/gergo/scripts/check_time.sh
