#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II 

bspc config border_width         4
bspc config window_gap         	 0
bspc config top_padding          5 
bspc config right_padding        5 
bspc config bottom_padding       5 
bspc config left_padding         5 


bspc config top_monocle_padding  -5 
bspc config right_monocle_padding -5 
bspc config bottom_monocle_padding -5 
bspc config left_monocle_padding -5 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config normal_border_color '#7c6f64'
bspc config focused_border_color '#d79921'

bspc rule -a fzfmenu focus=on state=floating rectangle=800x500+560+290
bspc rule -a feh focus=on state=floating
bspc rule -a Xmessage focus=on state=floating

#
#scrips to load at start
#
feh --bg-fill ~/Pictures/wallp/wheat.jpg
#check if the theme set is time-appropriate; if not, change it
/home/gergo/scripts/check_time.sh
#refresh the epub&pdf database at every restart
/home/gergo/scripts/menus/zathura/refresh_db.sh
#turn off x bell
xset b off
